-- Generated by scripts/generate-seed.ts — do not edit by hand.
-- Idempotent: safe to re-run after catalog changes.

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('copper-renewal-serum', 'PT-SER-001', 'Copper Renewal Serum · GHK-Cu 2%', 'Serums', 5800, 4930, '30 ml', false, 60)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-CRS-001', '2026-06', '2027-12', '/coa/PT24-CRS-001.pdf', 240
from products where slug = 'copper-renewal-serum'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 240 from products where slug = 'copper-renewal-serum'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 240, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-CRS-001'
where p.slug = 'copper-renewal-serum'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('smooth-signal-serum', 'PT-SER-002', 'Smooth Signal Serum · Matrixyl 3000 + Argireline', 'Serums', 5200, 4420, '30 ml', false, 60)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-SSS-001', '2026-06', '2028-06', '/coa/PT24-SSS-001.pdf', 260
from products where slug = 'smooth-signal-serum'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 260 from products where slug = 'smooth-signal-serum'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 260, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-SSS-001'
where p.slug = 'smooth-signal-serum'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('daily-peptide-complex', 'PT-SER-003', 'Daily Peptide Complex · 10% Multi-Peptide', 'Serums', 4800, 4080, '30 ml', false, 80)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-DPC-001', '2026-07', '2028-07', '/coa/PT24-DPC-001.pdf', 320
from products where slug = 'daily-peptide-complex'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 320 from products where slug = 'daily-peptide-complex'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 320, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-DPC-001'
where p.slug = 'daily-peptide-complex'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('peptide-barrier-cream', 'PT-MOI-001', 'Peptide Barrier Cream · Ceramides + Tripeptide', 'Moisturizers', 4400, 3740, '50 ml', false, 70)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-PBC-001', '2026-06', '2028-06', '/coa/PT24-PBC-001.pdf', 300
from products where slug = 'peptide-barrier-cream'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 300 from products where slug = 'peptide-barrier-cream'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 300, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-PBC-001'
where p.slug = 'peptide-barrier-cream'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('peptide-gel-moisturizer', 'PT-MOI-002', 'Peptide Gel Moisturizer · HA + Hexapeptide', 'Moisturizers', 4200, 3570, '50 ml', false, 70)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-PGM-001', '2026-07', '2028-07', '/coa/PT24-PGM-001.pdf', 280
from products where slug = 'peptide-gel-moisturizer'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 280 from products where slug = 'peptide-gel-moisturizer'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 280, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-PGM-001'
where p.slug = 'peptide-gel-moisturizer'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('eye-revival-cream', 'PT-EYE-001', 'Eye Revival Cream · Eyeseryl + Caffeine', 'Eye & Lip', 3800, 3230, '15 ml', false, 50)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-ERC-001', '2026-06', '2028-06', '/coa/PT24-ERC-001.pdf', 220
from products where slug = 'eye-revival-cream'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 220 from products where slug = 'eye-revival-cream'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 220, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-ERC-001'
where p.slug = 'eye-revival-cream'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('peptide-lip-treatment', 'PT-EYE-002', 'Peptide Lip Treatment · Tripeptide + Shea', 'Eye & Lip', 2400, 2040, '10 ml', false, 100)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-PLT-001', '2026-07', '2028-07', '/coa/PT24-PLT-001.pdf', 400
from products where slug = 'peptide-lip-treatment'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 400 from products where slug = 'peptide-lip-treatment'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 400, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-PLT-001'
where p.slug = 'peptide-lip-treatment'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('hair-density-serum', 'PT-HAI-001', 'Hair Density Serum · Capixyl + Redensyl', 'Hair & Body', 4600, 3910, '60 ml', false, 45)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-HDS-001', '2026-06', '2028-06', '/coa/PT24-HDS-001.pdf', 180
from products where slug = 'hair-density-serum'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 180 from products where slug = 'hair-density-serum'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 180, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-HDS-001'
where p.slug = 'hair-density-serum'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('firming-body-lotion', 'PT-HAI-002', 'Firming Body Lotion · Tetrapeptide + Urea', 'Hair & Body', 3600, 3060, '200 ml', false, 50)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-FBL-001', '2026-07', '2028-07', '/coa/PT24-FBL-001.pdf', 210
from products where slug = 'firming-body-lotion'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 210 from products where slug = 'firming-body-lotion'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 210, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-FBL-001'
where p.slug = 'firming-body-lotion'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('collagen-peptides-powder', 'PT-ING-001', 'Collagen Peptides · Type I & III, Unflavored', 'Ingestibles', 3900, 3315, '300 g · 30 servings', true, 90)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-CPP-001', '2026-06', '2028-06', '/coa/PT24-CPP-001.pdf', 350
from products where slug = 'collagen-peptides-powder'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 350 from products where slug = 'collagen-peptides-powder'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 350, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-CPP-001'
where p.slug = 'collagen-peptides-powder'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('marine-collagen-sachets', 'PT-ING-002', 'Marine Collagen Sachets · + Vitamin C & Zinc', 'Ingestibles', 4900, 4165, '30 × 8 g sachets', true, 50)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-MCS-001', '2026-07', '2028-01', '/coa/PT24-MCS-001.pdf', 190
from products where slug = 'marine-collagen-sachets'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 190 from products where slug = 'marine-collagen-sachets'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 190, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-MCS-001'
where p.slug = 'marine-collagen-sachets'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);

insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)
values ('the-complete-routine', 'PT-BND-001', 'The Complete Routine · 4-Piece Set', 'Bundles', 12900, 10965, '4 full-size products', false, 30)
on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,
  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,
  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;

insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)
select id, 'PT24-BND-001', '2026-07', '2027-12', '/coa/PT24-BND-001.pdf', 120
from products where slug = 'the-complete-routine'
on conflict (lot) do nothing;

insert into inventory (product_id, stock)
select id, 120 from products where slug = 'the-complete-routine'
on conflict (product_id) do nothing;

insert into inventory_movements (product_id, batch_id, type, qty, reference)
select p.id, b.id, 'receive', 120, 'launch seed'
from products p join batches b on b.product_id = p.id and b.lot = 'PT24-BND-001'
where p.slug = 'the-complete-routine'
  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);
