# Lumenwright business plan workbook — content part B

MARKETING = [
    ("t", ["7 · DIGITAL MARKETING PLAN + SOCIAL STRATEGY"]),
    ("b", []),
    ("h", ["7.1 BRAND PILLARS (every piece of content maps to one)"]),
    ("th", ["Pillar", "Story", "Proof format"]),
    ("r", ["Resurrection", "Dead heirlooms brought back to light", "Before/after restorations, process video"]),
    ("r", ["Craft", "How light is actually made — bench, brass, glass, dimming curves", "Macro shots, 'why warm-dim matters' explainers"]),
    ("r", ["Savings with taste", "LED conversion that doesn't look like an office supply store", "Retrofit case studies with kWh + design photos"]),
    ("r", ["The machine", "AI reads your room; a human designs it", "Screen-capture demos, plan→reality reveals"]),
    ("b", []),
    ("h", ["7.2 SEO — WHERE THE BUYING INTENT ALREADY IS"]),
    ("th", ["Cluster", "Example keywords", "Page", "Priority"]),
    ("r", ["Restoration (local)", "chandelier repair near me · antique light restoration <metro> · rewire old chandelier", "Service pages + metro landing pages", "P0 — demand exists, supply is weak"]),
    ("r", ["Retrofit (commercial)", "led retrofit <metro> · fluorescent to led conversion cost · commercial lighting rebates <state>", "Retrofit page + ROI calculator (already built — a natural link magnet)", "P0"]),
    ("r", ["Vintage knowledge", "how to date an antique chandelier · are old chandeliers safe · sputnik chandelier history", "Blog/guides — top-funnel authority", "P1"]),
    ("r", ["Product", "warm dim candelabra led · plaster-in led channel · 2 inch trimless downlight", "Product pages (already indexed-ready)", "P1"]),
    ("n", ["Local moves: Google Business Profile with weekly photo posts (restorations are catnip); top-20 citations; review velocity (ask on delivery day, QR card in every crate); one metro landing page per service."]),
    ("b", []),
    ("h", ["7.3 CONTENT ENGINE — ONE RESTORATION FEEDS EVERYTHING"]),
    ("n", ["Every project is filmed. One restoration yields: 1 long-form YouTube (8–15 min process film) → 4–6 vertical clips (Reels/TikTok/Shorts) → 1 before/after carousel → 1 case-study page → 1 email → GBP posts. Batch production day: every other Friday. The niche precedent is proven — restoration/repair channels routinely build 100k+ audiences from bench footage; nobody owns 'chandelier surgeon' yet."]),
    ("b", []),
    ("h", ["7.4 SOCIAL STRATEGY BY PLATFORM"]),
    ("th", ["Platform", "Role", "Format", "Cadence", "12-mo KPI"]),
    ("r", ["Instagram", "Portfolio + designer credibility (trade watches here)", "Before/after carousels · process Reels · Stories from the bench", "4 posts + 3 Reels/wk", "8k followers · 50 designer DMs · top referral source for custom"]),
    ("r", ["TikTok", "Reach + the 'oddly satisfying' restoration audience", "Crystal cleaning, rewiring, first-light moments, ember-flicker demos", "3–5 clips/wk (reposts fine)", "1 breakout (>500k views) · 15k followers"]),
    ("r", ["YouTube", "Trust + search ('how to' + process films)", "Long-form restorations · retrofit case walkthroughs · dimming science", "2/mo long-form + Shorts", "5k subs · ranks for 'chandelier restoration'"]),
    ("r", ["Pinterest", "Renovation planners (12–18 mo intent)", "Finished rooms, fixture boards by style", "10 pins/wk (scheduled)", "Steady referral traffic to product pages"]),
    ("r", ["LinkedIn", "Commercial retrofit + acquisition-side credibility", "Case studies w/ kWh math · rebate deadline alerts · founder build-in-public", "2/wk", "20 audit requests sourced"]),
    ("r", ["Facebook/Nextdoor", "Local homeowners + estate/antique groups", "GBP cross-posts; genuinely helpful answers in antique groups (no pitching)", "2/wk + group participation", "Local referral flywheel"]),
    ("b", []),
    ("h", ["7.5 PAID MEDIA (starts M4, AFTER 5 case studies)"]),
    ("th", ["Channel", "Budget start → scale", "Target", "Kill rule"]),
    ("r", ["Google Local Services Ads", "$800/mo → $2k", "'Chandelier repair' + 'lighting installation' — pay per lead", "CPL > $80 for 3 wks"]),
    ("r", ["Google Search (exact clusters)", "$1,200/mo → $4k", "Retrofit + restoration intent terms; LP = audit booking / restoration intake", "CAC > segment ceiling (tab 4)"]),
    ("r", ["Meta retargeting", "$400/mo", "AI-plan users + site visitors → consult booking", "ROAS < 3 after 60 days"]),
    ("r", ["Meta prospecting", "$0 until Phase 2", "Lookalikes of consult bookers; creative = restoration video", "Never scale before retargeting works"]),
    ("b", []),
    ("h", ["7.6 EMAIL — THE AI-PLAN FOLLOW-UP (already capturing via Supabase)"]),
    ("th", ["Day", "Email", "Job"]),
    ("r", [0, "Your lighting plan (PDF render of the AI plan)", "Deliver value; set consult CTA"]),
    ("r", [2, "The one mistake in most <room> lighting", "Teach; build authority"]),
    ("r", [5, "What this looks like in real homes (case study)", "Proof"]),
    ("r", [9, "What it costs (honest ranges + payback)", "Qualify; kill price anxiety"]),
    ("r", [14, "20-minute designer review — calendar link", "Convert; last touch before monthly digest"]),
    ("n", ["Also: monthly 'From the Bench' digest (1 restoration, 1 tip, 1 open slot) — the long-cycle nurture for 12-month renovators."]),
    ("b", []),
    ("h", ["7.7 BUDGET + FUNNEL TARGETS"]),
    ("th", ["Period", "Monthly budget", "Expected leads", "Consults", "Projects", "Blended CAC check"]),
    ("r", ["M1–3 (organic+founding)", "$500 (tools/boosts)", "30", "12", "6 (founding)", "n/a — proof phase"]),
    ("r", ["M4–6 (paid pilot)", "$2,500", "60", "18", "6–8", "≤$450 res / ≤$1,200 comm"]),
    ("r", ["M7–12 (scale winners)", "$4,000–6,000", "100+", "30", "10–14", "Same ceilings; kill losers monthly"]),
    ("b", []),
    ("h", ["7.8 12-WEEK LAUNCH SOCIAL CALENDAR (repeatable skeleton)"]),
    ("th", ["Week", "Hero content", "Supporting posts"]),
    ("r", ["1", "Launch film: 'Why we bring dead light back'", "Founder intro · bench tour · GBP launch post"]),
    ("r", ["2", "Restoration #1 long-form (YouTube)", "3 clips · before/after carousel · dossier close-up"]),
    ("r", ["3", "AI Studio demo (photo → plan in 60s)", "Plan→reality split-screens · 'what the AI saw'"]),
    ("r", ["4", "Retrofit case: '<Client> cut lighting energy 58%'", "kWh math explainer · rebate deadline PSA (LinkedIn)"]),
    ("r", ["5–12", "Alternate: restoration film / retrofit case / craft explainer / designer feature", "Each hero → 4–6 cutdowns + 1 email + GBP; feature one founding designer/mo (their audience becomes yours)"]),
]

VENDORS = [
    ("t", ["8 · VENDORS + SOURCING — WHO MAKES EVERYTHING"]),
    ("n", ["Rule: two qualified sources per critical category before Phase 2. Named companies below are established, well-known suppliers to start diligence with — verify current terms directly; this is a sourcing map, not an endorsement list."]),
    ("b", []),
    ("h", ["8.1 SOURCING MAP BY CATEGORY"]),
    ("th", ["Category", "What", "Where to source (start here)", "Terms to target"]),
    ("r", ["LED engines & drivers", "COBs, modules, drivers for custom builds + Vela", "Drivers: Mean Well, Inventronics · COB/modules: Bridgelux, Citizen, Samsung LED · via distributors: Future Electronics, Arrow, DigiKey for protos", "Distributor accounts; datasheet + LM-80 on file for everything installed"]),
    ("r", ["Retrofit kits & lamps (resale)", "DLC-listed troffer kits, UFO high bays, track heads, warm-dim candelabra", "Search DLC Qualified Products List (designlights.org) then buy through electrical distribution: Rexel, CED, Graybar, City Electric · known retrofit brands to price: Keystone Technologies, Espen Technology, EarthTronics, RAB, Sylvania/LEDVANCE", "Contractor pricing account + NET-30; DLC listing verified per SKU (rebate eligibility!)"]),
    ("r", ["Vela Series ODM", "Linea channel, Punto downlight, Arco cove, Firma grazer, Scena controls", "Route A (speed): white-label from Alibaba Verified/Trade Assurance suppliers (search 'plaster-in aluminum profile LED', 'trimless 2 inch downlight') · Route B (quality): Taiwan/Korea ODMs via Taipei Int'l Lighting Show · Route C (US assembly): extrusions imported, boards + assembly domestic for 'assembled in USA' spec story", "Samples first, always · LM-79/LM-80 test reports · 30/70 payment (30% PO, 70% after 3rd-party inspection) · NNN agreement (not just NDA) for custom tooling · QIMA or SGS inspection every production PO"]),
    ("r", ["Restoration parts", "Sockets, cloth wire, arms, canopies, crystal, glass", "Grand Brass Lamp Parts (NY) · B&P Lamp Supply (TN, trade account) · crystal: import replacements via European/Egyptian crystal houses, match-service from strung samples · custom glass: local glassblowing studios (find via craft guilds + art schools)", "Trade accounts at both majors (resale cert required); keep a $2–3k parts library of the 50 most-used pieces"]),
    ("r", ["Antique fixture inventory", "One-of-ones for the Vintage collection", "Estate sales (EstateSales.net alerts) · architectural salvage: Olde Good Things and regional salvage yards · auctions: LiveAuctioneers/local auction houses · demolition contractors (call them — they throw chandeliers away) · 'we buy broken chandeliers' page on our own site", "Buy at ≤15% of expected restored retail; document provenance at purchase"]),
    ("r", ["Custom fabrication", "Machining, spinning, casting, powder coat, plating", "ThomasNet/Xometry for machined + sheet parts · local metal spinners + powder coaters (audit in person) · plating: regional job shops (nickel/brass) — restoration-grade matters", "2 shops per process; prototype tolerance agreement before first client job"]),
    ("r", ["Controls ecosystem", "Dimmers, wireless, DALI, keypads", "Lutron (residential + commercial programs) · Casambi partner program (wireless) · DALI-2 components via distribution", "Join Lutron/Casambi pro programs early — training + demo gear + spec listing"]),
    ("r", ["Crating & freight", "Insured fixture transport (ship-in restorations!)", "Custom crating: local crate shops or build in-house (jig on Ops list) · freight: FedEx Freight/regional LTL + Craters & Freighters for white-glove", "Declared-value insurance ALWAYS; photo protocol at pack + unpack"]),
    ("r", ["Lamp/ballast recycling", "Compliance disposal for retrofits", "National mail-back/box programs and regional universal-waste recyclers (search state environmental agency's approved list)", "Keep manifests 3 yrs; show clients the certificate — it sells"]),
    ("b", []),
    ("h", ["8.2 TRADE SHOWS & SOURCING CALENDAR"]),
    ("th", ["Event", "When/where (verify dates)", "Go for"]),
    ("r", ["LEDucation", "Mar · NYC", "Architectural LED suppliers, controls, cheap to attend — best first show"]),
    ("r", ["LightFair", "Rotates (major US lighting show)", "Retrofit OEMs, DLC vendors, rep relationships"]),
    ("r", ["Light + Building", "Frankfurt · biennial (even yrs)", "Design direction + European component sources — Phase 3 trip"]),
    ("r", ["Hong Kong Int'l Lighting Fair", "Oct · HK", "ODM speed-dating for Vela — bring the spec book"]),
    ("r", ["High Point Market", "Apr + Oct · NC", "Where interior designers shop — sell side, not buy side"]),
    ("b", []),
    ("h", ["8.3 VENDOR VETTING CHECKLIST (any vendor > $5k/yr)"]),
    ("n", ["□ Business verified (registry/D&B or Alibaba Verified+years) □ 3 references or review history □ Sample evaluated on OUR test rig (dimmer wall, CCT meter) □ Test reports where applicable (LM-79/LM-80, UL/ETL cert numbers verified on UL database) □ Written lead times + late-delivery remedy □ Payment terms in writing □ Second source identified □ For ODM: NNN signed, tooling ownership stated, inspection rights in PO"]),
    ("b", []),
    ("h", ["8.4 MADE-TO-ORDER FULFILLMENT FLOW (matches the Supabase order pipeline)"]),
    ("th", ["Step", "Actor", "System state (order_requests.status)"]),
    ("r", ["Client configures + requests order", "Site", "new"]),
    ("r", ["We confirm options/price/lead time; take 50% deposit", "Founder", "confirmed"]),
    ("r", ["PO to manufacturer/fabricator with spec pack", "Founder", "sent_to_manufacturer"]),
    ("r", ["Inspection (photos or 3rd-party for Vela POs) → ship/crate", "Vendor + us", "sent_to_manufacturer"]),
    ("r", ["Delivery/install + commissioning; balance collected; service record opened", "Us/EC sub", "fulfilled"]),
]

FUNDING = [
    ("t", ["9 · FUNDING STACK — SBA + COMPLEMENTS, AND STARTUP COSTS"]),
    ("b", []),
    ("h", ["9.1 STARTUP COSTS (one-time + first-6-months runway)"]),
    ("th", ["Category", "Item", "Amount"]),
    ("r", ["Legal & compliance", "LLC/registrations, contracts drafted (founding client, sub agreement, network terms), state filings", 3500]),
    ("r", ["Insurance", "GL + products/completed-ops + inland marine + commercial auto (6 mo premiums)", 5500]),
    ("r", ["Licensing path", "EC sub onboarding, permits float, owner course/exam fees", 2500]),
    ("r", ["Workshop equipment", "Restoration bench, rewiring tools, dimmer test wall, CCT/flicker meter, crating jig", 9500]),
    ("r", ["Vehicle", "Used cargo van + wrap + shelving", 21000]),
    ("r", ["Vela launch stock", "Samples + first production PO (capped)", 12000]),
    ("r", ["Restoration parts library", "Top-50 parts stock (Grand Brass/B&P opening orders)", 2500]),
    ("r", ["Brand & site", "Domain, email, photography kit (used FF camera + lights), print (audit one-pagers, crate QR cards)", 3000]),
    ("r", ["Marketing launch", "M1–6 budget incl. paid pilot (tab 7)", 9000]),
    ("r", ["Software/ops", "QuickBooks, field app, scheduling, misc SaaS (6 mo)", 1500]),
    ("r", ["Trade shows/sourcing", "LEDucation trip + ODM sample costs", 3000]),
    ("r", ["Working capital reserve", "6 mo fixed costs buffer (the 'sleep at night' line)", 40500]),
    ("r", ["Contingency", "10% of above", 5000]),
    ("th", ["TOTAL", "", 118500]),
    ("b", []),
    ("h", ["9.2 THE FUNDING STACK (recommended sequence)"]),
    ("th", ["Layer", "Amount", "Source", "Terms (typical — verify current)", "When"]),
    ("r", ["1. Owner injection", "$18,500", "Personal savings", "Equity — lenders want to see ~10–15% skin", "Now"]),
    ("r", ["2. SBA Microloan", "$50,000", "Nonprofit intermediary/CDFI (find via SBA Lender Match)", "≤$50k · ~8–13% · ≤7 yrs · faster + startup-friendly + free TA coaching", "Apply Jul, fund by Sep"]),
    ("r", ["3. Equipment financing", "$21,000", "Bank/credit union or dealer", "Van as collateral · 6–9% · 5 yrs · preserves cash vs buying outright", "At purchase (Aug)"]),
    ("r", ["4. SBA 7(a) Small", "$75,000–150,000", "SBA-preferred bank (community banks, Live Oak-style SBA specialists, Huntington)", "Prime + ~2.75–4.75% · ≤10 yrs working capital · personal guarantee + likely blanket lien", "Apply M4–6 WITH TRACTION (founding projects + this workbook + actuals) — approval odds and terms improve dramatically"]),
    ("r", ["5. SBA CAPLine / bank LOC", "$25,000–50,000", "Same lender as 7(a)", "Revolving; for retrofit WIP timing gaps", "Secure in M6–9 BEFORE it's needed"]),
    ("r", ["Later: SBA 504", "TBD", "CDC + bank", "Owner-occupied facility purchase, ~10% down, long fixed", "Phase 3 if buying the shop"]),
    ("n", ["Why staged: microloan now funds launch without betting everything on one approval; the 7(a) lands after 3–6 months of real revenue, which converts you from 'idea borrower' (hard) to 'traction borrower' (routine)."]),
    ("b", []),
    ("h", ["9.3 NON-DEBT COMPLEMENTS"]),
    ("th", ["Source", "Fit", "Notes"]),
    ("r", ["Customer deposits", "Core — negative working capital by design", "50% deposits are the cheapest financing that exists"]),
    ("r", ["Vendor terms", "NET-30/60 at distributors after 2–3 orders", "Ask at every account opening; it's free float"]),
    ("r", ["Utility on-bill financing / C-PACE", "Finances the CLIENT's retrofit, not us", "Closes deals without us carrying paper — learn local programs in Phase 0"]),
    ("r", ["State/utility efficiency grants", "Occasional small-biz energy grants", "Check state energy office + utility trade-ally programs; also register as a trade ally (lead source!)"]),
    ("r", ["Revenue-based financing / Stripe Capital", "Phase 2+, only against proven margin", "Expensive; use for inventory turns, never payroll"]),
    ("r", ["Angels/strategic", "Only for the Vela spinout thesis (Phase 4)", "Don't sell equity to fund a services launch that debt covers"]),
    ("b", []),
    ("h", ["9.4 LENDER READINESS CHECKLIST"]),
    ("n", ["□ This workbook (plan + forecast) □ Personal financial statement + 3 yrs personal returns □ Credit ≥680 (check + fix now) □ Owner injection documented (bank stmts) □ Entity docs, EIN, licenses/insurance certs □ Use-of-funds table (9.1) □ Collateral schedule (van, equipment, blanket lien expectation) □ DSCR story: forecast shows ≥1.25 coverage by M12 □ 2-min pitch: what, who pays, why you, why now □ Apply to 3 lenders in parallel — terms vary wildly"]),
    ("b", []),
    ("h", ["9.5 USE-OF-FUNDS TIMELINE"]),
    ("th", ["Month", "Deployed", "Purpose"]),
    ("r", ["Jul–Aug", "$38k", "Setup: legal, insurance, equipment, van (financed), samples, brand"]),
    ("r", ["Sep–Oct", "$25k", "Vela stock, parts library, launch marketing, working capital begins"]),
    ("r", ["Nov–Mar", "$45k", "Runway coverage while founding projects convert to full-price pipeline; paid media pilot"]),
    ("r", ["Reserve", "$10k+", "Untouched contingency — replenish before growth spending"]),
]
