# Lumenwright business plan workbook — content part A
# Row styles: t=title, h=section header, sh=subheader, th=table header,
# r=table row, k=key/value, n=note, b=blank

START_HERE = [
    ("t", ["LUMENWRIGHT — MASTER BUSINESS PLAN"]),
    ("n", ["The Light Atelier: custom lighting installations · vintage rehabilitation · rare chandelier repair · turnkey LED retrofit · Vela Series proprietary LED · AI Lighting Studio · Designer Network"]),
    ("n", ["Prepared July 7, 2026 · Living document — every number is an editable assumption, not a promise"]),
    ("b", []),
    ("h", ["HOW TO USE THIS WORKBOOK"]),
    ("k", ["1 · Business Plan", "The full plan: market, customers, competition, operations, team, risk. Read first."]),
    ("k", ["2 · GTM + Workback", "Go-to-market strategy and the dated week-by-week workback schedule to the Oct 1, 2026 launch."]),
    ("k", ["3 · Phased Approach", "Five phases from foundation to scale, each with entry/exit gates. Don't skip gates."]),
    ("k", ["4 · Revenue Engine", "How every dollar is made: six streams, unit economics, pricing, LTV/CAC, cash cycle."]),
    ("k", ["5 · Forecast", "36-month financial model with live formulas. Change the yellow assumption cells; everything recalculates."]),
    ("k", ["6 · Designer Network", "The supply side: recruiting, vetting, economics, and scaling the designer partner network."]),
    ("k", ["7 · Digital Marketing", "SEO, content, social strategy by platform, paid media, email, and the 12-week launch calendar."]),
    ("k", ["8 · Vendors + Sourcing", "Who actually makes and supplies everything — named suppliers, sourcing process, vetting checklist."]),
    ("k", ["9 · Funding + Startup Costs", "Itemized startup budget and the SBA-anchored funding stack, with lender requirements."]),
    ("b", []),
    ("h", ["THE TEN NUMBERS THAT MATTER"]),
    ("th", ["#", "Metric", "Target", "Why it matters"]),
    ("r", [1, "Launch date", "Oct 1, 2026", "Everything in the workback drives to this"]),
    ("r", [2, "Startup capital required", "$118,500", "See Funding tab — funded by ~$18.5k owner + ~$100k SBA"]),
    ("r", [3, "Lighthouse projects (Phase 1)", "10 by Mar 2027", "Case studies are the marketing engine; nothing scales without them"]),
    ("r", [4, "Year 1 revenue (conservative)", "≈$380,000", "Forecast tab base case — edit the yellow cells to make it yours"]),
    ("r", [5, "Blended gross margin", "≥45%", "Below 40% = pricing problem; fix before scaling"]),
    ("r", [6, "Cash-flow breakeven", "Month 10–12", "Made-to-order deposits make this achievable"]),
    ("r", [7, "Founding designers signed", "8 by Dec 2026", "Network gate for Phase 2"]),
    ("r", [8, "AI Studio → consult conversion", "≥8%", "The funnel's core efficiency metric"]),
    ("r", [9, "Customer acquisition cost", "≤$450 residential / ≤$1,200 commercial", "Payback in first project or the channel is off"]),
    ("r", [10, "5-yr service plan attach rate", "100% of turnkey projects", "This is the moat and the recurring revenue base"]),
    ("b", []),
    ("h", ["OPERATING PRINCIPLES"]),
    ("n", ["1. Deposits before parts — 50% on order, made-to-order only. Working capital stays positive."]),
    ("n", ["2. No claim we can't defend — licensing, savings math, and lead times are stated exactly."]),
    ("n", ["3. Every project produces an asset — photos, a case study, a review, a referral ask. No exceptions."]),
    ("n", ["4. The AI studio is a funnel, not a product. A human closes every deal."]),
    ("n", ["5. Retrofit pays the bills; restoration builds the brand; Vela builds the equity."]),
]

BUSINESS_PLAN = [
    ("t", ["1 · THE BUSINESS PLAN"]),
    ("b", []),
    ("h", ["1.1 COMPANY OVERVIEW"]),
    ("k", ["Legal form", "Single-member LLC (elect S-corp at ~$60k+ owner pay); registered in home state; DBA 'Lumenwright'"]),
    ("k", ["What we do", "One studio for the full life of light: design + build custom fixtures, restore vintage/rare fixtures, repair chandeliers, and convert buildings to LED under a turnkey program with 5 years of included service"]),
    ("k", ["Vertically integrated model", "Design → specification → procurement (manufacturer partners) → delivery → installation (licensed partner/staff) → 5-yr service. One accountable party."]),
    ("k", ["Proprietary product", "Vela Series architectural LED line (channel, downlight, cove, façade, controls) — third-party manufactured, spec'd through our projects first, sold to trade second"]),
    ("k", ["Technology edge", "AI Lighting Studio: photo → personalized 3-layer lighting plan → designer-reviewed consult. 24/7 lead qualification no competitor in the niche has."]),
    ("k", ["Assets already built", "Live website (Next.js/Vercel), Supabase operations database (catalog, orders, leads, referrals), designer network infrastructure, AI analysis pipeline"]),
    ("b", []),
    ("h", ["1.2 THE PROBLEM"]),
    ("n", ["Homeowners/designers with vintage fixtures have almost nowhere to take them — electricians won't touch crystal, and restorers won't touch wiring."]),
    ("n", ["Small/mid commercial buildings overpay for lighting energy because national ESCOs ignore projects under ~$250k and electricians sell hardware, not outcomes (no audit, no rebate filing, no service)."]),
    ("n", ["Design-driven clients can't buy 'one accountable party' — they assemble designer + showroom + electrician + handyman and absorb the seams."]),
    ("n", ["Independent lighting designers lose projects because they lack fabrication, product margin, and installation muscle behind them."]),
    ("b", []),
    ("h", ["1.3 MARKET (estimates — validate locally in Phase 0)"]),
    ("th", ["Segment", "Size signal", "Our slice (SOM logic)"]),
    ("r", ["US lighting fixtures market", "≈$30B+ annual, LED share still growing", "We are not chasing share; we are extracting high-margin niches"]),
    ("r", ["Commercial LED retrofit services", "Tens of $B remaining conversion backlog; ~half of US commercial floorspace still has fluorescent/HID", "Local SMB buildings 10k–100k sq ft: offices, gyms, warehouses, churches, retail"]),
    ("r", ["Lighting restoration/repair", "Fragmented cottage industry; no dominant brand; strong search demand, thin supply", "Regional monopoly potential within 12–18 months; national via ship-in commissions"]),
    ("r", ["Custom/decorative fixtures", "Growing 'quiet luxury' + hospitality refresh cycles", "5–15 statement pieces/yr at $5k–$15k+ each via designers"]),
    ("r", ["Architectural LED (Vela)", "Spec-driven; wins compound via designer relationships", "Attach to every project yr 1; third-party spec sales yr 2+"]),
    ("n", ["SOM sanity check: Year-1 plan requires ~2 retrofit projects + ~3 restorations + ~1 custom piece per month by month 12 in ONE metro. That is a rounding error of local demand."]),
    ("b", []),
    ("h", ["1.4 CUSTOMER SEGMENTS (ICPs)"]),
    ("th", ["ICP", "Profile", "Trigger moment", "What they buy first", "Avg first ticket"]),
    ("r", ["Heritage Homeowner", "Owns pre-1960 home or inherited fixtures; 45–75; values provenance", "Estate inheritance, renovation, a dead chandelier", "Restoration commission / relamp set", "$1,500–$6,000"]),
    ("r", ["Design-Led Renovator", "35–60, $150k+ HHI, working with (or wanting) a designer", "Kitchen/whole-home reno; saw a photo they loved", "AI plan → custom pendant/chandelier package", "$3,000–$12,000"]),
    ("r", ["SMB Owner-Operator", "Owns/controls building 10k–60k sq ft; pays own utility bill", "Utility bill spike; ballast failures; rebate deadline", "Free audit → turnkey retrofit", "$15,000–$60,000"]),
    ("r", ["Hospitality Operator", "Restaurant/boutique hotel, 1–5 locations", "Opening, refresh, or 'the room feels wrong'", "Design consult → feature fixtures + scenes", "$10,000–$40,000"]),
    ("r", ["Trade Partner (designer/architect/GC)", "Specs lighting but can't fabricate/install/service", "A project they can't staff", "Network membership → spec support + product", "$2,000–$20,000/project"]),
    ("b", []),
    ("h", ["1.5 COMPETITION & POSITIONING"]),
    ("th", ["Competitor type", "Their strength", "Their gap", "Our counter"]),
    ("r", ["National ESCOs (retrofit)", "Scale, financing", "Ignore sub-$250k projects; no design sensibility", "Turnkey for SMB; design-grade light quality; 5-yr service"]),
    ("r", ["Electrical contractors", "Licensed, local, trusted", "Sell hardware not outcomes; no audits/rebates/design", "We hand them work (network) instead of fighting them"]),
    ("r", ["Lighting showrooms", "Product selection", "No install, no custom, no service; margin-squeezed by e-comm", "Made-to-order + install + service; showrooms can become partners"]),
    ("r", ["Etsy/antique restorers", "Craft credibility", "No electrical compliance, no scale, no warranty", "Code-compliant restoration + dossier + 5-yr warranty"]),
    ("r", ["Online fixture retailers", "Price, breadth", "Zero service; commodity product", "We don't compete on price; we sell finished outcomes"]),
    ("k", ["Positioning statement", "For people and businesses who care what light does to a space, Lumenwright is the only studio that designs, builds, restores, converts, and then services light for five years — one accountable partner from photo to finished room."]),
    ("b", []),
    ("h", ["1.6 OPERATIONS PLAN"]),
    ("th", ["Area", "Plan", "Cost reference (Funding tab)"]),
    ("r", ["Facility", "Phase 0–1: home workshop/garage + storage unit for crating. Phase 2: 1,200–2,000 sq ft light-industrial bay (~$1,500–2,500/mo) with bench, spray/patina area, photo corner", "Facility line"]),
    ("r", ["Licensing (CRITICAL PATH)", "Do not advertise installation until solved. Options: (a) subcontract to licensed EC under written agreement — fastest, do this first; (b) hire licensed journeyman month 7–9; (c) owner pursues license long-term. Restoration bench work + retrofit kit supply are legal without EC license in most states — verify with state board in week 1.", "Legal/licensing line"]),
    ("r", ["Insurance", "GL $1M/$2M + products/completed ops; inland marine for client fixtures in shop (restoration!); commercial auto; workers comp at first hire; E&O once designing for trade", "Insurance line"]),
    ("r", ["Equipment", "Restoration bench (rewiring, plating prep, crystal pinning), test rig (dimmer wall!), crating station, van (used, wrapped)", "Equipment lines"]),
    ("r", ["Compliance", "Old lamp/ballast disposal = EPA Universal Waste rules — contract a certified recycler (e.g., national mail-back programs) and keep manifests; it's a selling point, not just a cost", "Ops line"]),
    ("r", ["Software stack", "Site+DB built ($0); add: QuickBooks, Jobber/ServiceTitan-lite for field, Stripe/Shopify when payments go live", "Software line"]),
    ("b", []),
    ("h", ["1.7 TEAM & HIRING PLAN"]),
    ("th", ["When", "Role", "Type", "Comp target", "Trigger"]),
    ("r", ["Now", "Founder — design, sales, bench, everything", "Owner", "$3–4k/mo draw until M6, then $6k", "—"]),
    ("r", ["M3–M6", "Licensed electrical sub (per-project)", "1099/sub", "15–22% of install labor line", "First install sold"]),
    ("r", ["M7–M9", "Restoration/bench tech (craft hands)", "PT→FT", "$22–28/hr", "Bench backlog > 3 weeks"]),
    ("r", ["M9–M12", "Licensed journeyman electrician", "FT", "$70–90k + van", "≥2 retrofits/mo for 3 straight months"]),
    ("r", ["M12–M18", "Ops/project coordinator", "FT", "$50–60k", "Founder >30% time on scheduling"]),
    ("r", ["M18+", "Second crew / designer-in-residence", "FT", "Market", "Phase 3 gates met"]),
    ("b", []),
    ("h", ["1.8 RISK REGISTER"]),
    ("th", ["Risk", "Likelihood", "Impact", "Mitigation"]),
    ("r", ["Licensing/regulatory misstep", "Med", "High", "Sub-first model; state board verification in writing; never advertise beyond scope"]),
    ("r", ["Founder capacity (everything on one person)", "High", "High", "Ruthless phase gates; sub/PT help early; the workback has slack built in"]),
    ("r", ["Retrofit price competition", "Med", "Med", "Compete on turnkey outcome + service, never on $/fixture; walk from bid wars"]),
    ("r", ["Vela ODM quality failure", "Med", "High", "Third-party inspection every PO; LM-79/80 reports; dual-source by yr 2; never spec into a project without stock on hand"]),
    ("r", ["A damaged heirloom in our care", "Low", "Severe", "Inland marine insurance; intake condition documentation (photo+video); conservative promise-making"]),
    ("r", ["Utility rebate program changes", "Med", "Med", "Rebates framed as bonus not basis; track programs quarterly; diversify streams"]),
    ("r", ["Cash crunch from growth", "Med", "High", "50% deposits; CAPLine/LOC in place BEFORE needed (Funding tab); weekly 13-week cash forecast"]),
    ("r", ["Designer network conflict (channel vs direct)", "Low", "Med", "Clear rules of engagement in founding-member agreement; designers always own the client they bring"]),
    ("b", []),
    ("h", ["1.9 KPIs — REVIEWED WEEKLY"]),
    ("th", ["Funnel", "Economics", "Delivery", "Brand"]),
    ("r", ["Site visits · AI plans run · consults booked · close rate", "GM% by stream · CAC by channel · payback (days) · cash weeks on hand", "On-time delivery % · punch-list items/project · service response hrs", "Reviews (count/rating) · case studies published · designer NPS"]),
]

GTM = [
    ("t", ["2 · GO-TO-MARKET + WORKBACK SCHEDULE"]),
    ("b", []),
    ("h", ["2.1 GTM STRATEGY IN ONE PARAGRAPH"]),
    ("n", ["Launch Oct 1, 2026 in ONE metro with two spearheads: (1) the Founding Client Program — 10 lighthouse projects sold at cost-plus in exchange for full case-study rights, reviews, and referrals; (2) the free commercial lighting audit, pitched直direct to 100 hand-picked SMB buildings. The AI Studio is the top of funnel for everything; every plan ends in a human consult. Designers are recruited in parallel (tab 6) so that by Phase 2 the network is a second sales force. We do not do broad paid media until case studies exist."]),
    ("b", []),
    ("h", ["2.2 OFFER LADDER (how strangers become $40k clients)"]),
    ("th", ["Step", "Offer", "Price", "Purpose"]),
    ("r", [1, "AI Lighting Plan (photo → plan)", "Free", "Capture + qualify; deliver instant value"]),
    ("r", [2, "Designer review call (20 min)", "Free", "Human trust; scope the real project"]),
    ("r", [3, "Paid design consult / commercial audit", "$150–$500 (credited to project)", "Commitment filter; audit produces the savings analysis"]),
    ("r", [4, "Project (restore / custom / retrofit)", "$1.5k–$60k", "Core revenue"]),
    ("r", [5, "5-yr service plan (turnkey: included)", "Included / $29–99/mo standalone", "Retention moat + recurring base"]),
    ("b", []),
    ("h", ["2.3 CHANNEL PRIORITY (first 6 months)"]),
    ("th", ["Rank", "Channel", "Target", "Why now"]),
    ("r", [1, "Founding Client Program (direct outreach + personal network)", "10 projects by Mar", "Case studies before ad spend"]),
    ("r", [2, "Direct commercial outreach (100-building list)", "20 audits, 6 conversions", "Highest ticket, controllable"]),
    ("r", [3, "Google Business Profile + local SEO", "Top-3 map pack for 'chandelier repair <metro>'", "Restoration demand already searches; low competition"]),
    ("r", [4, "Designer/trade recruitment", "8 founding members", "Compounding channel"]),
    ("r", [5, "Organic social (restoration content)", "Content bank of 30 posts", "Feeds everything later; near-zero cost now"]),
    ("r", ["Hold", "Paid search/social", "Start M4+ only after 5 case studies", "Ads amplify proof; they don't create it"]),
    ("b", []),
    ("h", ["2.4 WORKBACK SCHEDULE — TO OCT 1, 2026 LAUNCH (today = Jul 7)"]),
    ("th", ["Week of", "Workstream", "Deliverable (done = shippable)", "Owner"]),
    ("r", ["Jul 7", "Legal/Compliance", "LLC filed; EIN; state electrical-board scope ruling requested IN WRITING; insurance quotes ordered", "Founder"]),
    ("r", ["Jul 7", "Funding", "SBA package started: this workbook + personal financial stmt; 3 lender/CDFI intros requested (Lender Match)", "Founder"]),
    ("r", ["Jul 14", "Ops", "GL + inland marine bound; lamp-recycler contract signed; bench equipment ordered", "Founder"]),
    ("r", ["Jul 14", "Product", "Vela ODM shortlist (5 candidates) contacted; sample POs for Linea + Punto; retrofit kit distributor accounts opened (2 min.)", "Founder"]),
    ("r", ["Jul 21", "Brand/Site", "Real business name/entity decision locked; site lib/site.ts updated (name, inboxes, credentials); domain purchased + connected on Vercel", "Founder"]),
    ("r", ["Jul 21", "Sales assets", "Commercial audit one-pager; restoration intake form; founding-client agreement drafted", "Founder"]),
    ("r", ["Jul 28", "Licensing", "Electrical sub agreement signed with 1–2 licensed ECs (rate card + insurance certs on file)", "Founder"]),
    ("r", ["Jul 28", "Network", "Designer prospect list built (50 names: IALD/ALA/IES rosters + IG); outreach sequence written", "Founder"]),
    ("r", ["Aug 4", "Founding clients", "Founding Client Program page live; 25 personal-network invitations sent; 100-building commercial list built (county records + walk-the-street)", "Founder"]),
    ("r", ["Aug 4", "Content", "First restoration documented start-to-finish (own/thrifted fixture if no client yet) — 200+ photos, video", "Founder"]),
    ("r", ["Aug 11", "Product", "Vela samples received → test rig validation (dimming curves, CCT, flicker); accept/reject; production PO for launch stock", "Founder"]),
    ("r", ["Aug 11", "Sales", "First 3 founding projects signed (any mix); first commercial audits booked (target 5)", "Founder"]),
    ("r", ["Aug 18", "Marketing", "GBP live + 10 photos; local citations (top 20 directories); review flow tested end-to-end", "Founder"]),
    ("r", ["Aug 18", "Ops", "Supabase order/lead pipeline drilled: order → confirm → manufacturer PO → delivery → service record. Test with founding project #1", "Founder"]),
    ("r", ["Aug 25", "Funding", "SBA application submitted (microloan or 7(a) small per Funding tab decision)", "Founder"]),
    ("r", ["Aug 25", "Content", "Case study #1 published (site + GBP + social); email sequence for AI-plan leads written (5 emails)", "Founder"]),
    ("r", ["Sep 1", "Sales", "Founding projects 4–6 signed; 2 retrofit audits delivered with savings analysis; first retrofit proposal out", "Founder"]),
    ("r", ["Sep 8", "Network", "First 3 designer applications through vetting; founding-member terms finalized from their feedback", "Founder"]),
    ("r", ["Sep 8", "Site", "Payments decision executed (Stripe deposits recommended); env vars set; live order flow tested with real card", "Founder"]),
    ("r", ["Sep 15", "Marketing", "Launch content batch produced: 12 posts scheduled, launch email written, PR pitch to 5 local outlets ('the chandelier surgeon' angle)", "Founder"]),
    ("r", ["Sep 22", "Dress rehearsal", "Full dry run: AI plan → consult → proposal → deposit on a real prospect; fix every seam found", "Founder"]),
    ("r", ["Sep 29", "LAUNCH WEEK", "Public launch Oct 1: PR out, launch email, GBP posts, first retrofit install scheduled, review engine on", "Founder"]),
    ("b", []),
    ("h", ["2.5 POST-LAUNCH 90 DAYS (Oct–Dec)"]),
    ("th", ["Month", "Focus", "Exit criteria"]),
    ("r", ["Oct", "Deliver founding projects flawlessly; weekly content from real work", "3 projects delivered; 5 reviews; audit pipeline ≥ 8"]),
    ("r", ["Nov", "Convert audit pipeline; first designer-sourced project", "2 retrofits closed; 5 designers active; CAC data by channel"]),
    ("r", ["Dec", "Paid media pilot ($2k) on proven message; 2027 plan from real data", "10 lighthouse projects done → Phase 1 gate review (tab 3)"]),
]

PHASED = [
    ("t", ["3 · PHASED APPROACH — GATES, NOT DATES"]),
    ("n", ["Dates are targets; gates are law. A phase ends only when its exit gates are met. If a gate fails twice, the plan is wrong — revise it, don't force it."]),
    ("b", []),
    ("th", ["Phase", "Window (target)", "Theme", "Key activities", "Investment", "EXIT GATES (all required)"]),
    ("r", ["Phase 0 — Foundation", "Jul–Sep 2026", "Legal, capital, assets, pipeline", "Everything in the Workback (tab 2): entity, insurance, licensing path, SBA app, Vela samples, founding-client recruitment, designer outreach", "≈$45k (setup portion of startup budget)", "Insurance bound · EC sub signed · funding approved or bank-balance runway ≥9 mo · 6 founding projects signed · site live on real domain"]),
    ("r", ["Phase 1 — Proof", "Oct 2026–Mar 2027", "10 lighthouse projects, case-study engine", "Deliver founding projects at cost-plus; 20 commercial audits; publish 8+ case studies; 8 founding designers; paid media pilot; service plans attached to every turnkey job", "≈$35k ops + marketing pilot", "10 projects delivered · ≥15 reviews at 4.8+ · blended GM ≥40% · CAC known per channel · 2 designer-sourced projects · cash ≥ plan"]),
    ("r", ["Phase 2 — Traction", "Apr–Dec 2027", "Repeatable revenue machine", "Hire journeyman + bench tech; retrofit becomes 50%+ of revenue; Vela attaches to every project; raise prices 10–15% off proof; scale winning ad channels; 15 active designers", "Funded by operations + remaining SBA", "$70k+/mo revenue for 3 consecutive months · GM ≥45% · founder <25% time on delivery · service base ≥30 contracts"]),
    ("r", ["Phase 3 — Scale", "2028", "Second metro via network + Vela trade sales", "Designer-led expansion (no office): 5+ designers in metro #2 with local EC subs; Vela sold to non-project trade (reps/distribution); coordinator + crew #2; consider 504 loan for facility purchase", "New capital decision point (LOC/504/retained earnings)", "Metro #2 ≥$25k/mo · Vela third-party ≥15% of product revenue · EBITDA ≥15%"]),
    ("r", ["Phase 4 — Platform", "2029+", "Optionality", "Choose deliberately: (a) regional dominance + cash cow; (b) Vela spinout as product company; (c) franchise/license the model + software to other operators; (d) strategic sale (the About-page thesis: integrated platform + product line + network = attractive acquisition)", "Depends on path", "Owner's call — the business supports all four"]),
    ("b", []),
    ("h", ["PHASE-GATE REVIEW RITUAL"]),
    ("n", ["Last Friday of each phase-end month: score every gate red/green with evidence (numbers from the Forecast tab actuals column). Two reds = phase extends one quarter and ONE root cause gets fixed. Never carry more than one red into a new phase."]),
]

REVENUE = [
    ("t", ["4 · REVENUE ENGINE — HOW EVERY DOLLAR IS MADE"]),
    ("b", []),
    ("h", ["4.1 SIX REVENUE STREAMS — UNIT ECONOMICS"]),
    ("th", ["Stream", "Avg ticket", "COGS", "Gross margin", "Sales cycle", "Volume lever", "Notes"]),
    ("r", ["1. Turnkey LED retrofit", "$28,000", "Kits+labor+disposal ≈ 58%", "≈42%", "3–8 wks (audit→close)", "Audits booked/mo", "Rebates improve CLIENT math, not our margin — we also charge $350–500 rebate filing (often waived to close)"]),
    ("r", ["2. Restoration & chandelier repair", "$2,800", "Parts+plating+bench hrs ≈ 40%", "≈60%", "1–3 wks", "Bench capacity; ship-in commissions are unbounded by geography", "Highest margin + highest brand value; photograph everything"]),
    ("r", ["3. Custom fixtures", "$7,500", "Fabrication partners ≈ 55%", "≈45%", "4–10 wks", "Designer relationships", "50% deposit funds the build — negative working capital"]),
    ("r", ["4. Vela Series product", "$1,800/order", "ODM landed ≈ 45–55%", "≈45–55%", "0–4 wks", "Spec attach rate; trade accounts", "Internal projects yr 1; third-party trade sales yr 2+ is the equity story"]),
    ("r", ["5. Service plans", "$588/yr equiv", "Truck time ≈ 30%", "≈70%", "Attached at sale", "Installed base", "Included in turnkey price (priced in!); standalone $29–99/mo for non-turnkey clients"]),
    ("r", ["6. Design fees & audits", "$150–$500", "Founder time", "≈90%", "Days", "AI Studio volume", "Credited to projects — a filter that pays for itself"]),
    ("b", []),
    ("h", ["4.2 PRICING STRATEGY"]),
    ("n", ["Value-based, never cost-plus (except founding clients, deliberately). Retrofit priced against the CLIENT's savings: target ≤30-month payback for them, which supports our 42%+ margin. Restoration priced per documented assessment — the dossier justifies the invoice. Custom priced by statement value, floor at 45% GM. Raise prices 10–15% at Phase 2 entry; proof removes price sensitivity."]),
    ("n", ["Optional retrofit closer for hesitant SMBs: shared-savings pilot (we finance one zone, split verified savings 50/50 for 24 mo) — use sparingly, max 1 active pilot, it's a sales tool not a business model."]),
    ("b", []),
    ("h", ["4.3 LTV / CAC BY SEGMENT"]),
    ("th", ["Segment", "First ticket GM", "Expansion path", "3-yr LTV (GM)", "CAC ceiling (payback ≤ 1st project)"]),
    ("r", ["Heritage Homeowner", "$1,700", "2nd fixture · relamp sets · referrals (avg 1.3)", "≈$4,200", "$450"]),
    ("r", ["Design-Led Renovator", "$3,400", "Whole-home phases · service plan · designer referral loop", "≈$8,000", "$450"]),
    ("r", ["SMB Retrofit", "$11,800", "2nd building · controls upgrade · service base · referrals", "≈$21,000", "$1,200"]),
    ("r", ["Hospitality", "$9,000", "Location #2+ · seasonal re-lamping · scene updates", "≈$19,000", "$1,500"]),
    ("r", ["Trade partner", "$2,500/proj", "Every future project they spec", "≈$15,000+", "$800 (recruiting cost)"]),
    ("b", []),
    ("h", ["4.4 CASH MODEL — WHY THIS BUSINESS IS CASH-FRIENDLY"]),
    ("n", ["Made-to-order + 50% deposits = we hold client cash before we owe suppliers. Retrofit: 50/40/10 (deposit/delivery/completion). Custom: 50/50. Restoration: assessment fee upfront + 50% on quote approval. Vela stock is the ONLY inventory risk — cap initial stock at $12k and reorder against backlog."]),
    ("n", ["Discipline: 13-week rolling cash forecast every Monday; deposits are project cash, not payroll — track WIP liability explicitly in QuickBooks."]),
    ("b", []),
    ("h", ["4.5 MARGIN WATERFALL TARGET (steady state, Phase 2)"]),
    ("th", ["Line", "% of revenue"]),
    ("r", ["Blended COGS", "≈54%"]),
    ("r", ["Gross margin", "≈46%"]),
    ("r", ["Marketing", "8–10%"]),
    ("r", ["Ops/facility/insurance/software", "10–12%"]),
    ("r", ["Payroll (non-COGS)", "12–15%"]),
    ("r", ["EBITDA target", "12–16%"]),
]

DESIGNER = [
    ("t", ["6 · DESIGNER NETWORK PLAN — THE SUPPLY SIDE"]),
    ("n", ["The network solves geography and licensing without payroll, and turns the AI Studio into a two-sided funnel. Concierge-first (hand-matched), honest about being new. Site infrastructure already live: /designers page, referral + application pipelines in Supabase."]),
    ("b", []),
    ("h", ["6.1 VALUE EXCHANGE"]),
    ("th", ["Designers give us", "We give designers"]),
    ("r", ["Local delivery capacity in their metro", "Qualified, pre-scoped leads (room, fixture direction, budget band from AI Studio) — free during founding period"]),
    ("r", ["Spec loyalty to Vela + catalog", "Trade pricing: 25% off list (we retain ~15–20% margin)"]),
    ("r", ["Case studies + co-branded content", "Fabrication + restoration bench behind their designs"]),
    ("r", ["A referral fee on projects we source later (10%, post-founding)", "Retrofit program support: audits, financial analysis, rebate filing under their brand if desired"]),
    ("b", []),
    ("h", ["6.2 RECRUITING FUNNEL — 8 FOUNDING MEMBERS BY DEC 2026"]),
    ("th", ["Stage", "Target #", "How"]),
    ("r", ["Prospect list", "50", "IALD + ALA member directories · IES local section rosters · Instagram/Houzz search ('lighting designer <metro>') · showroom staff going independent"]),
    ("r", ["Personal outreach", "50", "Individual notes referencing THEIR work (never blast); offer: founding member, zero fees, shape the terms"]),
    ("r", ["Discovery calls", "20", "30 min: their pipeline, their gaps, our support menu"]),
    ("r", ["Applications", "12", "Via /designers form (portfolio, region, specialties)"]),
    ("r", ["Vetted + signed", "8", "Rubric below + founding-member agreement"]),
    ("b", []),
    ("h", ["6.3 VETTING RUBRIC (score 1–5 each; ≥18 to join; no 1s)"]),
    ("th", ["Criterion", "What good looks like"]),
    ("r", ["Portfolio quality", "Layered light, warm palettes, glare discipline — our aesthetic language"]),
    ("r", ["References", "2 client + 1 contractor reference, called personally"]),
    ("r", ["Professionalism", "Responds inside 2 business days; carries insurance; contracts in writing"]),
    ("r", ["Coverage & capacity", "Serves a definable metro; can take ≥2 projects/quarter"]),
    ("r", ["Values fit", "Comfortable with honest claims culture; no spec-and-disappear artists"]),
    ("b", []),
    ("h", ["6.4 FOUNDING MEMBER TERMS (v1 — refine with first 3 signees)"]),
    ("k", ["Term", "12 months, renewable; either party exits with 30 days notice, active projects protected"]),
    ("k", ["Fees", "Zero platform fees during founding period; leads we send are free; post-founding: 10% referral on Lumenwright-sourced project design fees"]),
    ("k", ["Product", "25% trade discount; Vela spec support incl. photometrics; NET-15 after first 3 orders"]),
    ("k", ["Standards", "1-business-day response SLA to intros; client survey after each project; co-marketing rights (both ways, approval required)"]),
    ("k", ["Exclusivity", "None — but 'Founding Member' badge is limited to 10, ever"]),
    ("b", []),
    ("h", ["6.5 ENABLEMENT KIT (ship within 1 week of signing)"]),
    ("n", ["Welcome box: Vela Linea + Punto samples, candelabra warm-dim set, finish chips · Spec binder (cut sheets, IES files) · Co-branded audit one-pager · Directory profile live on /designers · Intro to their local EC sub where we have one"]),
    ("b", []),
    ("h", ["6.6 NETWORK SCORECARD (monthly)"]),
    ("th", ["Metric", "Target"]),
    ("r", ["Intro → response within SLA", "100%"]),
    ("r", ["Intro → project conversion", "≥30%"]),
    ("r", ["Client satisfaction (post-project survey)", "≥4.7/5"]),
    ("r", ["Designer product orders/quarter", "≥1 per active member"]),
    ("r", ["Designer NPS", "≥60"]),
    ("b", []),
    ("h", ["6.7 EXPANSION RULE"]),
    ("n", ["Open metro #2 only when: 3+ vetted applicants there + 10+ organic AI-plan leads/month from that metro + one anchor designer willing to co-launch. Network-led expansion costs ≈$3k (travel + enablement kits), not an office."]),
]
