// Regenerates supabase/seed.sql from lib/products.ts so the DB
// catalog can never drift from the storefront catalog.
//   node --experimental-strip-types scripts/generate-seed.ts

import { writeFileSync } from "fs";
import { join } from "path";
import { products } from "../lib/products.ts";

const q = (s: string) => `'${s.replaceAll("'", "''")}'`;

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  "-- Idempotent: safe to re-run after catalog changes.",
  "",
];

for (const p of products) {
  lines.push(
    `insert into products (slug, sku, name, category, price, subscribe_price, size, ingestible, reorder_point)`,
    `values (${q(p.slug)}, ${q(p.sku)}, ${q(p.name)}, ${q(p.category)}, ${p.price}, ${p.subscribePrice}, ${q(p.size)}, ${p.ingestible}, ${p.reorderPoint})`,
    `on conflict (slug) do update set sku = excluded.sku, name = excluded.name, category = excluded.category,`,
    `  price = excluded.price, subscribe_price = excluded.subscribe_price, size = excluded.size,`,
    `  ingestible = excluded.ingestible, reorder_point = excluded.reorder_point;`,
    "",
    `insert into batches (product_id, lot, manufactured_on, best_by, coa_url, received_qty)`,
    `select id, ${q(p.batch.lot)}, ${q(p.batch.mfg)}, ${q(p.batch.exp)}, ${q(p.batch.coaPath)}, ${p.stock}`,
    `from products where slug = ${q(p.slug)}`,
    `on conflict (lot) do nothing;`,
    "",
    `insert into inventory (product_id, stock)`,
    `select id, ${p.stock} from products where slug = ${q(p.slug)}`,
    `on conflict (product_id) do nothing;`,
    "",
    `insert into inventory_movements (product_id, batch_id, type, qty, reference)`,
    `select p.id, b.id, 'receive', ${p.stock}, 'launch seed'`,
    `from products p join batches b on b.product_id = p.id and b.lot = ${q(p.batch.lot)}`,
    `where p.slug = ${q(p.slug)}`,
    `  and not exists (select 1 from inventory_movements m where m.reference = 'launch seed' and m.product_id = p.id);`,
    "",
  );
}

const out = join(import.meta.dirname, "..", "supabase", "seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out}`);
